
name: CBStats
version: 1.0.0
main: stats\StatsClass
api:
- 3.0.0
- 4.0.0
author: Aleondev
permissions:
 stats.command:
  deafult: true

commands:
 stats:
   description: ยง6Stats ยง7Command
   permission: stats.command
